# Generated by Django 3.2.5 on 2021-07-05 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0002_auto_20210705_1307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='lan_mac_address',
            field=models.CharField(max_length=17),
        ),
        migrations.AlterField(
            model_name='device',
            name='wlan_mac_address',
            field=models.CharField(max_length=17),
        ),
    ]
