# Generated by Django 3.2.5 on 2021-07-05 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0003_auto_20210705_1321'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='device_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Desktop PC'), (2, 'Notebook PC'), (3, 'Tablet Device'), (4, 'WiFi Hotspot'), (5, 'Projector'), (6, 'IP Phone'), (7, 'Document Camera'), (8, 'High-Def TV'), (9, 'Drone'), (10, 'Camera Tri-Pod')], default=2),
        ),
        migrations.AlterField(
            model_name='device',
            name='imei_number',
            field=models.PositiveBigIntegerField(verbose_name='IMEI Number'),
        ),
        migrations.AlterField(
            model_name='device',
            name='lan_mac_address',
            field=models.CharField(max_length=17, verbose_name='LAN MAC Address'),
        ),
        migrations.AlterField(
            model_name='device',
            name='replacement_fee',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6, verbose_name='Replacement Fee'),
        ),
        migrations.AlterField(
            model_name='device',
            name='serial_number',
            field=models.CharField(max_length=50, verbose_name='Serial Number'),
        ),
        migrations.AlterField(
            model_name='device',
            name='wlan_mac_address',
            field=models.CharField(max_length=17, verbose_name='WLAN MAC Address'),
        ),
    ]
