# Generated by Django 3.2.5 on 2021-07-05 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0004_auto_20210705_1424'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='device_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Select Device Type'), (2, 'Desktop PC'), (3, 'Notebook PC'), (4, 'Tablet Device'), (5, 'WiFi Hotspot'), (6, 'Projector'), (7, 'IP Phone'), (8, 'Document Camera'), (9, 'High-Def TV'), (10, 'Swivl'), (11, 'Drone'), (12, 'Camera Tri-Pod')], default=1),
        ),
        migrations.AlterField(
            model_name='device',
            name='manufacturer',
            field=models.PositiveSmallIntegerField(choices=[(100, 'Choose Manufacturer'), (99, 'Apple'), (98, 'Casio'), (97, 'Dell'), (96, 'DJI'), (95, 'Epson'), (94, 'Hewlett-Packard (HP)'), (93, 'Logitech'), (92, 'Mitel'), (91, 'Philips'), (90, 'Samsung'), (89, 'ShoreTel'), (88, 'Sony'), (87, 'Supersonic'), (86, 'Swivl')], default=100),
        ),
    ]
