# Generated by Django 3.2.5 on 2021-07-05 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0005_auto_20210705_1511'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_id', models.CharField(max_length=20, verbose_name='Tag ID')),
                ('qr_code', models.ImageField(blank=True, null=True, upload_to='', verbose_name='QR Code')),
            ],
            options={
                'verbose_name': 'Asset Tag',
                'verbose_name_plural': 'Asset Tags',
            },
        ),
    ]
