# Generated by Django 3.2.5 on 2021-07-05 18:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0006_assettag'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='asset_tag',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='devices.assettag', verbose_name='Asset Tag'),
        ),
        migrations.AlterField(
            model_name='device',
            name='imei_number',
            field=models.PositiveBigIntegerField(null=True, verbose_name='IMEI Number'),
        ),
        migrations.AlterField(
            model_name='device',
            name='lan_mac_address',
            field=models.CharField(max_length=17, null=True, verbose_name='LAN MAC Address'),
        ),
        migrations.AlterField(
            model_name='device',
            name='manufacturer',
            field=models.PositiveSmallIntegerField(choices=[(100, 'Choose Manufacturer'), (99, 'Apple'), (98, 'Casio'), (97, 'Dell'), (96, 'DJI'), (95, 'Epson'), (94, 'HP'), (93, 'Logitech'), (92, 'Mitel'), (91, 'Philips'), (90, 'Samsung'), (89, 'ShoreTel'), (88, 'Sony'), (87, 'Supersonic'), (86, 'Swivl')], default=100),
        ),
        migrations.AlterField(
            model_name='device',
            name='wlan_mac_address',
            field=models.CharField(max_length=17, null=True, verbose_name='WLAN MAC Address'),
        ),
    ]
