# Generated by Django 3.2.5 on 2021-07-05 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0009_auto_20210705_2020'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='replacement_fee',
        ),
        migrations.AlterField(
            model_name='device',
            name='device_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Select Device Type'), (2, 'Desktop PC'), (3, 'Document Camera'), (4, 'Drone'), (5, 'High-Def TV'), (6, 'WiFi Hotspot'), (7, 'IP Phone'), (8, 'Laptop PC (>=8GB RAM)'), (9, 'Laptop Charger'), (10, 'Notebook PC (<8GB RAM)'), (11, 'Notebook Charger'), (12, 'Projector'), (13, 'Swivl'), (14, 'Tablet'), (15, 'Tablet Charger'), (16, 'Tri-Pod Stand')], default=1, verbose_name='Device Type'),
        ),
        migrations.AlterField(
            model_name='device',
            name='make_and_model',
            field=models.PositiveSmallIntegerField(choices=[(100, 'Choose Device Make - Model'), (99, 'Apple - iPad mini (1st Gen, Model A1432)'), (98, 'Apple - iPad mini 2 (2nd Gen, Model A1489)'), (97, 'Apple - iPad (6th Gen, Model A1893)'), (96, 'Apple - iPad (8th Gen, Model A2270)'), (95, 'Dell - OptiPlex 3020 (Teacher-grade PC)'), (94, 'Dell - Chromebook 3100 (USB-C charger)'), (93, 'HP - Chromebook 11A G8 EE (USB-C charger)'), (92, 'HP - Chromebook 11-v031nr (AC Adapter, blue-tip plug)'), (91, 'HP - ProDesk 400 G6 SFF (Lab-grade PC)'), (90, 'HP - ProDesk 600 G5 SFF (Teacher-grade PC)'), (89, 'Lenovo - 300e (2nd Gen.)'), (88, 'Lenovo - ThinkPad L450'), (87, 'Lenovo - ThinkPad L540')], default=100, verbose_name='Make & Model'),
        ),
    ]
