# Generated by Django 3.2.5 on 2021-07-12 20:31

import devices.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0011_alter_device_device_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Borrower',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=30, verbose_name='Last Name')),
                ('email', models.EmailField(max_length=254, unique=True, validators=[devices.models.validate_borrower_email], verbose_name='Email Address')),
                ('school_type', models.PositiveSmallIntegerField(choices=[(1, 'Choose School Type'), (2, 'Laker Elementary School'), (3, 'Laker Middle School'), (4, 'Laker High School'), (5, 'Laker S.A.I.L. Academy')], default=1, verbose_name='School Type')),
                ('school_building', models.PositiveSmallIntegerField(choices=[(10, 'Select School Buidling'), (11, 'Elementary Building'), (12, 'Secondary Building'), (13, 'S.A.I.L Academy Building')], default=10, verbose_name='School Building')),
                ('account_balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=6, verbose_name='Account Balance')),
            ],
        ),
    ]
