# Generated by Django 3.2.5 on 2021-07-16 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0012_borrower'),
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='School Name')),
                ('building', models.PositiveSmallIntegerField(choices=[(0, 'Select School Buidling'), (1, 'Elementary Building'), (2, 'Secondary Building'), (3, 'S.A.I.L Academy Building')], default=((0, 'Select School Buidling'), (1, 'Elementary Building'), (2, 'Secondary Building'), (3, 'S.A.I.L Academy Building')), verbose_name='School Building')),
            ],
        ),
    ]
