# Generated by Django 3.2.5 on 2021-07-16 17:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0013_school'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrower',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='devices.school'),
        ),
    ]
