# Generated by Django 3.2.5 on 2021-07-16 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0014_borrower_school'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=50, unique=True, verbose_name='Type of Device')),
                ('sn_available', models.BooleanField(verbose_name='S/N (Serial Number) available for this device')),
                ('imei_available', models.BooleanField(verbose_name='IMEI (International Mobile Equipment Identity) number available for this device')),
                ('lan_mac_available', models.BooleanField(verbose_name='LAN (ethernet) MAC address available for this device')),
                ('wlan_mac_available', models.BooleanField(verbose_name='WLAN (wireless) MAC address available for this device')),
                ('live_stream', models.BooleanField(verbose_name='Used for live-streamed school events')),
                ('inperson_learning', models.BooleanField(verbose_name='Used for in-person learning')),
                ('virtual_learning', models.BooleanField(verbose_name='Used for virtual learning')),
            ],
            options={
                'verbose_name': 'Device Type',
                'verbose_name_plural': 'Device Types',
            },
        ),
    ]
