# Generated by Django 3.2.5 on 2021-07-16 19:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0015_devicetype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='device_type',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='devices.devicetype', verbose_name='Device Type'),
        ),
    ]
