# Generated by Django 3.2.5 on 2021-07-19 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0017_auto_20210716_2010'),
    ]

    operations = [
        migrations.CreateModel(
            name='GraduationYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveSmallIntegerField(verbose_name='Graduation Year')),
            ],
            options={
                'verbose_name': 'Graduation Year',
                'verbose_name_plural': 'Graduation Years',
            },
        ),
    ]
