# Generated by Django 3.2.5 on 2021-07-21 09:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0018_graduationyear'),
    ]

    operations = [
        migrations.CreateModel(
            name='BorrowerType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
            options={
                'verbose_name': 'Borrower Type',
                'verbose_name_plural': 'Borrower Types',
            },
        ),
        migrations.AddField(
            model_name='borrower',
            name='borrower_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='devices.borrowertype'),
        ),
    ]
