# Generated by Django 3.2.5 on 2021-07-22 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0020_auto_20210721_1007'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, unique=True)),
            ],
            options={
                'verbose_name': 'City',
                'verbose_name_plural': 'Cities',
            },
        ),
    ]
