# Generated by Django 3.2.5 on 2021-07-22 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0021_city'),
    ]

    operations = [
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=20, unique=True)),
                ('abbreviation', models.CharField(blank=True, max_length=2, unique=True)),
            ],
        ),
    ]
