# Generated by Django 3.2.5 on 2021-07-22 14:26

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0022_state'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactInfoEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_1', models.CharField(max_length=50, unique=True, verbose_name='Address (line 1)')),
                ('address_2', models.CharField(blank=True, max_length=50, null=True, verbose_name='Address (line 2)')),
                ('zip_code', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(regex='\\d{5}|\\d[5]-\\d{4}')], verbose_name='Zip Code')),
                ('primary_phone', models.CharField(max_length=16, validators=[django.core.validators.RegexValidator(regex='^\\+?1?\\d{8,15}$')], verbose_name='Primary Contact Number')),
                ('primary_phone_type', models.PositiveSmallIntegerField(choices=[(3, 'Mobile'), (2, 'Home'), (1, 'Work')], null=True, verbose_name='Primary Contact Number Type')),
                ('secondary_phone', models.CharField(blank=True, max_length=16, null=True, validators=[django.core.validators.RegexValidator(regex='^\\+?1?\\d{8,15}$')], verbose_name='Secondary Contact Number')),
                ('secondary_phone_type', models.PositiveSmallIntegerField(blank=True, choices=[(3, 'Mobile'), (2, 'Home'), (1, 'Work')], null=True, verbose_name='Secondary Contact Number Type')),
                ('city', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='devices.city')),
                ('state', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='devices.state')),
            ],
            options={
                'verbose_name': 'Contact Info Entry',
                'verbose_name_plural': 'Contact Info Entries',
            },
        ),
    ]
