# Generated by Django 3.2.5 on 2021-07-22 16:46

import devices.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0024_auto_20210722_1636'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrower',
            name='laker_email',
            field=models.EmailField(default='example@lakerschools.org', max_length=254, unique=True, validators=[devices.models.validate_laker_email, devices.models.validate_email_address], verbose_name='Laker Email Address'),
        ),
        migrations.AlterField(
            model_name='contactinfoentry',
            name='primary_phone_type',
            field=models.PositiveSmallIntegerField(choices=[(2, 'Home'), (3, 'Mobile'), (1, 'Work')], null=True, verbose_name='Primary Contact Number Type'),
        ),
        migrations.AlterField(
            model_name='contactinfoentry',
            name='secondary_phone_type',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(2, 'Home'), (3, 'Mobile'), (1, 'Work')], null=True, verbose_name='Secondary Contact Number Type'),
        ),
    ]
