# Generated by Django 3.2.5 on 2021-07-22 16:49

import devices.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0025_auto_20210722_1646'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrower',
            name='secondary_email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True, validators=[devices.models.validate_email_address], verbose_name='Secondary Email Address'),
        ),
        migrations.AlterField(
            model_name='contactinfoentry',
            name='primary_phone_type',
            field=models.PositiveSmallIntegerField(choices=[(2, 'Home'), (1, 'Work'), (3, 'Mobile')], null=True, verbose_name='Primary Contact Number Type'),
        ),
        migrations.AlterField(
            model_name='contactinfoentry',
            name='secondary_phone_type',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(2, 'Home'), (1, 'Work'), (3, 'Mobile')], null=True, verbose_name='Secondary Contact Number Type'),
        ),
    ]
