# Generated by Django 3.2.5 on 2021-07-22 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0026_auto_20210722_1649'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceMaker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name': 'Device Maker',
                'verbose_name_plural': 'Device Makers',
            },
        ),
        migrations.RemoveField(
            model_name='device',
            name='manufacturer',
        ),
        migrations.AddField(
            model_name='device',
            name='device_maker',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True, verbose_name='Device Maker'),
        ),
        migrations.AlterField(
            model_name='contactinfoentry',
            name='primary_phone_type',
            field=models.PositiveSmallIntegerField(choices=[(3, 'Mobile'), (1, 'Work'), (2, 'Home')], null=True, verbose_name='Primary Contact Number Type'),
        ),
        migrations.AlterField(
            model_name='contactinfoentry',
            name='secondary_phone_type',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(3, 'Mobile'), (1, 'Work'), (2, 'Home')], null=True, verbose_name='Secondary Contact Number Type'),
        ),
    ]
