# Generated by Django 3.2.5 on 2021-07-22 20:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0029_auto_20210722_2024'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_date', models.DateTimeField(auto_now_add=True, verbose_name='Transaction Date')),
                ('asset', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='devices.asset')),
                ('borrower', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='devices.borrower')),
                ('transaction_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='devices.transactiontype', verbose_name='Transaction Type')),
            ],
        ),
    ]
