# Generated by Django 3.2.5 on 2021-07-23 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0030_transaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='replacement_fee',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6, verbose_name='Replacement Fee'),
        ),
        migrations.AlterField(
            model_name='contactinfoentry',
            name='primary_phone_type',
            field=models.PositiveSmallIntegerField(choices=[(2, 'Home'), (3, 'Mobile'), (1, 'Work')], null=True, verbose_name='Primary Phone Number Type'),
        ),
        migrations.AlterField(
            model_name='contactinfoentry',
            name='secondary_phone_type',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(2, 'Home'), (3, 'Mobile'), (1, 'Work')], null=True, verbose_name='Secondary Phone Number Type'),
        ),
    ]
