# Generated by Django 3.2.5 on 2021-07-23 11:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0036_auto_20210723_1049'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asset',
            name='borrower',
        ),
        migrations.AlterField(
            model_name='borrower',
            name='graduation_year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='devices.graduationyear', verbose_name='Graduation Year (if applicable)'),
        ),
        migrations.AlterField(
            model_name='borrower',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='devices.school', verbose_name='School of Enrollment (if applicable)'),
        ),
        migrations.AlterField(
            model_name='contactinfoentry',
            name='primary_phone_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Work'), (3, 'Mobile'), (2, 'Home')], null=True, verbose_name='Primary Phone Number Type'),
        ),
        migrations.AlterField(
            model_name='contactinfoentry',
            name='secondary_phone_type',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Work'), (3, 'Mobile'), (2, 'Home')], null=True, verbose_name='Secondary Phone Number Type'),
        ),
    ]
