# Generated by Django 3.2.5 on 2021-07-23 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0037_auto_20210723_1110'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='transaction_type',
        ),
        migrations.AddField(
            model_name='asset',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(2, 'Decommissioned'), (6, 'Stolen'), (4, 'Lost'), (3, 'In Stock'), (5, 'Under Repair'), (1, 'Checked Out')], default=3, verbose_name='Status'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='action',
            field=models.PositiveSmallIntegerField(choices=[(3, 'Report Damage'), (5, 'Report Lost'), (1, 'Check-In'), (6, 'Report Stolen'), (4, 'Report Dysfunctional'), (2, 'Check-Out')], null=True),
        ),
        migrations.AlterField(
            model_name='contactinfoentry',
            name='primary_phone_type',
            field=models.PositiveSmallIntegerField(choices=[(2, 'Home'), (3, 'Mobile'), (1, 'Work')], null=True, verbose_name='Primary Phone Number Type'),
        ),
        migrations.AlterField(
            model_name='contactinfoentry',
            name='secondary_phone_type',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(2, 'Home'), (3, 'Mobile'), (1, 'Work')], null=True, verbose_name='Secondary Phone Number Type'),
        ),
        migrations.DeleteModel(
            name='TransactionType',
        ),
    ]
