# Generated by Django 3.2.5 on 2021-08-12 20:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0038_auto_20210723_1204'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asset',
            name='status',
        ),
        migrations.AddField(
            model_name='asset',
            name='borrower',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='devices.borrower'),
        ),
        migrations.AlterField(
            model_name='borrower',
            name='borrower_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='devices.borrowertype', verbose_name='Borrower Type'),
        ),
        migrations.AlterField(
            model_name='contactinfoentry',
            name='primary_phone_type',
            field=models.PositiveSmallIntegerField(choices=[(3, 'Mobile'), (1, 'Work'), (2, 'Home')], default=3, verbose_name='Primary Phone Number Type'),
        ),
        migrations.AlterField(
            model_name='contactinfoentry',
            name='secondary_phone_type',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(3, 'Mobile'), (1, 'Work'), (2, 'Home')], null=True, verbose_name='Secondary Phone Number Type'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='action',
            field=models.PositiveSmallIntegerField(choices=[(6, 'Report Stolen'), (4, 'Report Dysfunctional'), (5, 'Report Lost'), (3, 'Report Damage'), (1, 'Check-In'), (2, 'Check-Out')], null=True),
        ),
    ]
